name: Dev Deployment
on:
  push:
    branches:
      - main

jobs:
  Unit_Test:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v4

        - name: Set up Python
          uses: actions/setup-python@v4
          with:
            python-version: 3.12

        - name: Install dependencies
          run: |
            python -m venv .venv
            source .venv/bin/activate
            pip install pytest

        - name: Run tests
          run: |
            source .venv/bin/activate
            python3 -m pytest --maxfail=1 --disable-warnings --cov=app --cov-report=term-missing --cov-report=xml -q
  SonarQube_Scan:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v4

        - name: Set up Python
          uses: actions/setup-python@v4
          with:
            python-version: 3.12

        - name: SonarQube Scan
          uses: sonarsource/sonarqube-scan-action@master
          env:
            SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
            SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

        # - name: Install dependencies
        #   run: |
        #     python -m venv .venv
        #     source .venv/bin/activate
        #     pip install pytest pytest-cov sonar-scanner

        # - name: Run tests and generate coverage report
        #   run: |
        #     source .venv/bin/activate
        #     python3 -m pytest --maxfail=1 --disable-warnings --cov=app --cov-report=term-missing --cov-report=xml -q

        # - name: SonarQube Scan
        #   env:
        #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        #   run: |
        #     sonar-scanner \
        #       -Dsonar.projectKey=web-app \
        #       -Dsonar.sources=. \
        #       -Dsonar.host.url=https://sonarcloud.io \
        #       -Dsonar.login=$SONAR_TOKEN \
        #       -Dsonar.python.coverage.reportPaths=coverage.xml
  Build:
    needs: [Unit_Test, SonarQube_Scan]
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v4

        - name: login to docker hub
          uses: docker/login-action@v4
          with:
            username: ${{ vars.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_TOKEN }}

        - name: Get short commit tag
          run: echo "short_tag=${GITHUB_SHA::7}" >> $GITHUB_ENV

        - name: Docker build and push
          uses: docker/build-push-action@v7
          with:
            context: .
            push: true
            tags: |
              ${{ vars.DOCKER_USERNAME }}/web-app:latest
              ${{ vars.DOCKER_USERNAME }}/web-app:${{ env.short_tag }}
  Deploy:
    needs: Build
    runs-on: ubuntu-latest
    steps:
        - name: setup ssh
          run: |
            mkdir -p ~/.ssh
            echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
            chmod 400 ~/.ssh/id_rsa
            ssh-keyscan -H ${{ vars.EC2_HOST }} >> ~/.ssh/known_hosts

        - name: Get short commit tag
          run: echo "short_tag=${GITHUB_SHA::7}" >> $GITHUB_ENV
        
        - name: Deploy to EC2
          run: |
            ssh -i ~/.ssh/id_rsa ${{ vars.EC2_USER }}@${{ vars.EC2_HOST }} << EOF
              cd /home/ubuntu/web-app
              export IMAGE_TAG=${{ env.short_tag }}
              echo ${IMAGE_TAG}
              docker compose pull
              docker compose up -d
            EOF

          